// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'menuitem-label'
  | 'pref-api-key'
  | 'pref-auto-context'
  | 'pref-claude-path'
  | 'pref-claude-path-placeholder'
  | 'pref-custom-instructions'
  | 'pref-excluded-tags'
  | 'pref-help'
  | 'pref-language'
  | 'pref-max-turns'
  | 'pref-model'
  | 'pref-proxy-port'
  | 'pref-section-api-fallback'
  | 'pref-section-claude-code'
  | 'pref-section-context'
  | 'pref-section-general'
  | 'pref-section-personalization'
  | 'pref-title'
  | 'pref-username'
  | 'prefs-title'
  | 'sidenav-clautero-tooltip'
  | 'startup-begin'
  | 'startup-finish';
