// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'menuitem-label'
  | 'pref-api-key'
  | 'pref-api-key-placeholder'
  | 'pref-auto-context'
  | 'pref-help'
  | 'pref-model'
  | 'pref-obsidian-api-key'
  | 'pref-obsidian-enabled'
  | 'pref-obsidian-vault-prefix'
  | 'pref-proxy-port'
  | 'pref-section-api'
  | 'pref-section-context'
  | 'pref-section-obsidian'
  | 'pref-title'
  | 'prefs-title'
  | 'sidenav-clautero-tooltip'
  | 'startup-begin'
  | 'startup-finish';
