// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "language": string;
      "username": string;
      "customInstructions": string;
      "excludedTags": string;
      "claudePath": string;
      "model": string;
      "maxTurns": number;
      "apiKey": string;
      "proxyPort": number;
      "autoContext": boolean;
    };
  }
}
